# Generated by Django 3.1.2 on 2020-12-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAI_app_v2', '0040_auto_20201229_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurysignup',
            name='allotted_cat',
            field=models.CharField(choices=[('Residential (bungalow, row houses, standalone buildings)', 'Residential (bungalow, row houses, standalone buildings)'), ('Residential (housing complex)', 'Residential (housing complex)'), ('Residential ( affordable housing)', 'Residential ( affordable housing)'), ('Commercial (malls, office, institution, hotel, hospital, cinema)', 'Commercial (malls, office, institution, hotel, hospital, cinema)'), ('Industrial (any size, any type)', 'Industrial (any size, any type)'), ('Infrastructure (bridges, flyovers, ESR etc.)', 'Infrastructure (bridges, flyovers, ESR etc.)'), ('Well equipped, well mechanized site', 'Well equipped, well mechanized site'), ('Government, Semi-Govt., Public Works', 'Government, Semi-Govt., Public Works'), ('Work upto Bare Shell (includes RCC, Masonry and Plaster works)', 'Work upto Bare Shell (includes RCC, Masonry and Plaster works)')], max_length=100),
        ),
    ]
